services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t ebostijancic/siberiancms .
  - docker push ebostijancic/siberiancms

deploy:
  provider: script
  script: docker push ebostijancic/siberiancms
  on:
    branch: master